#!/usr/bin/env bash
# =============================================================================
# audit-bsa-brand.sh  —  Bitcoin Sovereign Academy brand-consistency detector
#
# READ-ONLY. Scans the repo and writes a single markdown report at
#   reports/bsa-brand-consistency-audit.md
# It does NOT edit any HTML/CSS/JS/data/source file. It is idempotent:
# re-running only overwrites the report.
#
# Usage:  scripts/audit-bsa-brand.sh
# =============================================================================
# Audit script: counts patterns that may legitimately be absent (grep exit 1)
# and uses grep|wc pipelines, so we intentionally do NOT use -e or pipefail.
set -u

# --- Resolve repo root (parent of this script's directory) -------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPORT_DIR="$ROOT/reports"
REPORT="$REPORT_DIR/bsa-brand-consistency-audit.md"
mkdir -p "$REPORT_DIR"

# --- Canonical definitions ---------------------------------------------------
CANON_CSS=( "brand.css" "tokens.css" "design-tokens.css" "brand-consistency.css" )
TOKEN_CSS_RE='brand\.css|tokens\.css|design-tokens\.css'   # "linked a token source"
ORANGE_RE='#(ff7a00|f7931a|f2a900|ffd400|ffb800)'          # case-insensitive
HIRISK_DIRS=( paths deep-dives interactive-demos quizzes ai-tutors ai-agents certificates )

# --- File discovery (exclusions baked in) ------------------------------------
# Excludes: .git .worktrees .superpowers node_modules archive audit-* frontend
# drafts *_files and any hidden/build/vendor/cache dir. HTML only.
find_html() {
  find "$ROOT" -type d \( \
       -name '.?*' -o -name 'node_modules' -o -name 'archive' -o -name 'audit-*' \
    -o -name 'frontend' -o -name 'drafts' -o -name '*_files' \
    -o -name 'dist' -o -name 'build' -o -name '.cache' -o -name 'vendor' -o -name 'coverage' \
  \) -prune -o -type f -name '*.html' -print
}
rel() { sed "s|^$ROOT/||"; }
list_html() { find_html | rel | sort; }
topdir() { awk -F/ '{print ($2==""?"(root)":$1)}'; }

# Grep helpers that never fail the script (set -e safe)
g() { grep "$@" 2>/dev/null || true; }

# --- Gather core data --------------------------------------------------------
ALL_HTML="$(list_html)"
TOTAL=$(printf '%s\n' "$ALL_HTML" | sed '/^$/d' | wc -l | tr -d ' ')

# Pages linking each canonical CSS
declare -A CANON_COUNT
for c in "${CANON_CSS[@]}"; do
  CANON_COUNT[$c]=$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -lF "$c" 2>/dev/null | wc -l | tr -d ' ')
done

# Pages linking ANY token source vs missing
LINKED_TOKEN="$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -lE "$TOKEN_CSS_RE" 2>/dev/null | rel | sort || true)"
MISSING_TOKEN="$(comm -23 <(printf '%s\n' "$ALL_HTML" | sed '/^$/d') <(printf '%s\n' "$LINKED_TOKEN" | sed '/^$/d'))"
MISSING_COUNT=$(printf '%s\n' "$MISSING_TOKEN" | sed '/^$/d' | wc -l | tr -d ' ')

# Hardcoded orange/gold pages
HARDCODE_PAGES="$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -liE "$ORANGE_RE" 2>/dev/null | rel | sort || true)"
HARDCODE_COUNT=$(printf '%s\n' "$HARDCODE_PAGES" | sed '/^$/d' | wc -l | tr -d ' ')

# Inline style orange/gold
INLINE_PAGES="$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -liE "style=\"[^\"]*$ORANGE_RE" 2>/dev/null | rel | sort || true)"
INLINE_COUNT=$(printf '%s\n' "$INLINE_PAGES" | sed '/^$/d' | wc -l | tr -d ' ')

# data-* injected pages
DATA_RE='data-answer=|data-correct=|data-topic=|data-path=|data-lab=|data-demo-id=|data-btc-live=|data-email-capture='
DATA_PAGES="$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -lE "$DATA_RE" 2>/dev/null | rel | sort || true)"
DATA_COUNT=$(printf '%s\n' "$DATA_PAGES" | sed '/^$/d' | wc -l | tr -d ' ')

# --- Write the report --------------------------------------------------------
{
echo "# BSA Brand-Consistency Audit (detection-only)"
echo
echo "_Generated by \`scripts/audit-bsa-brand.sh\` on $(date '+%Y-%m-%d %H:%M %Z'). Read-only: no source files were modified._"
echo
echo "Canonical brand orange: **#FF7A00** (\`--color-brand\`). Canonical token sources: \`css/brand.css\`, \`css/tokens.css\`, \`css/design-tokens.css\`. Active overlay: \`css/brand-consistency.css\`."
echo
echo "Exclusions: \`.git\` \`.worktrees\` \`.superpowers\` \`node_modules\` \`archive\` \`audit-2026-04\` \`frontend\` \`drafts\` \`*_files\` and hidden/build/vendor/cache dirs. PDFs/DOCX/print are not HTML and are not scanned."
echo

echo "## Executive summary"
echo
echo "- Total scanned HTML pages: **$TOTAL**"
echo "- Pages linking a canonical token source ($TOKEN_CSS_RE): **$((TOTAL-MISSING_COUNT))**"
echo "- Pages missing any canonical token source: **$MISSING_COUNT**"
echo "- Pages with hardcoded brand orange/gold: **$HARDCODE_COUNT**"
echo "- Pages with inline orange/gold styles: **$INLINE_COUNT**"
echo "- Pages using \`data-*\` auto-injection (screenshot-QA required before edits): **$DATA_COUNT**"
echo
echo "Detection-only map. No BSA orange is neutralized; nothing is edited. Treat orange/gold drift as a canonicalization opportunity, not a removal."
echo

echo "## Counts by directory"
echo
echo "| Directory | HTML pages |"
echo "|---|---|"
printf '%s\n' "$ALL_HTML" | sed '/^$/d' | topdir | sort | uniq -c | sort -rn | awk '{printf "| %s | %s |\n",$2,$1}'
echo

echo "## Pages linking canonical brand/token CSS"
echo
echo "| Stylesheet | Pages linking |"
echo "|---|---|"
for c in "${CANON_CSS[@]}"; do echo "| \`css/$c\` | ${CANON_COUNT[$c]} |"; done
echo

echo "## Missing canonical stylesheet inventory"
echo
echo "Pages linking **none** of \`brand.css\`/\`tokens.css\`/\`design-tokens.css\` (count: **$MISSING_COUNT**), by directory:"
echo
echo "| Directory | Pages missing canonical |"
echo "|---|---|"
printf '%s\n' "$MISSING_TOKEN" | sed '/^$/d' | topdir | sort | uniq -c | sort -rn | awk '{printf "| %s | %s |\n",$2,$1}'
echo
echo "<details><summary>Full list of pages missing canonical token CSS</summary>"
echo
printf '%s\n' "$MISSING_TOKEN" | sed '/^$/d' | sed 's/^/- /'
echo
echo "</details>"
echo

echo "## Hardcoded orange/gold inventory"
echo
echo "Detected hex values: \`#FF7A00\` \`#f7931a\` \`#F2A900\` \`#FFD400\` \`#FFB800\` (case-insensitive). Pages: **$HARDCODE_COUNT**."
echo
echo "| Directory | Pages with hardcoded orange/gold |"
echo "|---|---|"
printf '%s\n' "$HARDCODE_PAGES" | sed '/^$/d' | topdir | sort | uniq -c | sort -rn | awk '{printf "| %s | %s |\n",$2,$1}'
echo
echo "Occurrences by exact value (across scanned HTML):"
echo
echo "| Value | Matches |"
echo "|---|---|"
for v in '#FF7A00' '#f7931a' '#F2A900' '#FFD400' '#FFB800'; do
  m=$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -hoiE "$v" 2>/dev/null | wc -l | tr -d ' ')
  echo "| \`$v\` (any case) | $m |"
done
echo

echo "## Inline orange/gold inventory"
echo
echo "Pages with \`style=\"...orange...\"\`: **$INLINE_COUNT**, by directory:"
echo
echo "| Directory | Pages with inline orange/gold |"
echo "|---|---|"
printf '%s\n' "$INLINE_PAGES" | sed '/^$/d' | topdir | sort | uniq -c | sort -rn | awk '{printf "| %s | %s |\n",$2,$1}'
echo

echo "## Token definition inventory (CSS variables defining brand/orange/gold)"
echo
echo "Variable declarations matching brand/orange/gold/primary across \`css/*.css\`:"
echo
echo '```'
g -rniE '^\s*--[a-z0-9-]*(brand|orange|gold|primary)[a-z0-9-]*\s*:' "$ROOT/css" | rel | sort
echo '```'
echo
echo "_Note: more than one file defining \`--color-brand\`/orange indicates overlapping sources of truth — flag for a later scoped consolidation report (no edits here)._"
echo

echo "## Brand-fix CSS inventory"
echo
echo "| File | Lines | Pages linking |"
echo "|---|---|---|"
for f in $(cd "$ROOT/css" 2>/dev/null && ls -1 *brand*fix*.css brand-consistency.css 2>/dev/null | sort -u); do
  [ -f "$ROOT/css/$f" ] || continue
  lines=$(wc -l < "$ROOT/css/$f" | tr -d ' ')
  links=$(printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -lF "$f" 2>/dev/null | wc -l | tr -d ' ')
  echo "| \`css/$f\` | $lines | $links |"
done
echo
echo "_Files linked by 0 pages may be orphaned (verify they are not JS-injected before any archival). Heavily-linked overlays are load-bearing and need their own scoped review._"
echo

echo "## Data/component auto-injection inventory"
echo
echo "Pages using auto-injection placeholders ($DATA_RE): **$DATA_COUNT**. Grep undercounts rendered UI on these pages — **screenshot QA required** before any future edit."
echo
echo "Most-used \`data-*\` attributes (top 25):"
echo
echo "| data-attribute | Occurrences |"
echo "|---|---|"
printf '%s\n' "$ALL_HTML" | sed "s|^|$ROOT/|" | xargs -r grep -hoE 'data-[a-z0-9-]+=' 2>/dev/null | sort | uniq -c | sort -rn | head -25 | awk '{printf "| `%s` | %s |\n",$2,$1}'
echo

echo "## Semantic/state color protect list"
echo
echo "These encode meaning and must NOT be treated as brand orange. State-color definitions found in \`css/*.css\`:"
echo
echo '```'
g -rniE '\.(correct|incorrect|right|wrong|success|warning|error|danger|valid|invalid|complete|completed|active|passed|failed|risk-(low|medium|high))\b' "$ROOT/css" | rel | sort | head -80
echo '```'
echo
echo "Quiz answer signals in HTML: \`data-correct=\` and \`data-answer=\` (see auto-injection inventory). Protect green/red/amber result colors and quiz states in any future work."
echo

echo "## High-risk manual zones"
echo
echo "| Zone | HTML pages | data-* pages |"
echo "|---|---|---|"
for d in "${HIRISK_DIRS[@]}"; do
  [ -d "$ROOT/$d" ] || continue
  hp=$(printf '%s\n' "$ALL_HTML" | sed '/^$/d' | grep -c "^$d/" || true)
  dp=$(printf '%s\n' "$DATA_PAGES" | sed '/^$/d' | grep -c "^$d/" || true)
  echo "| \`$d/\` | $hp | $dp |"
done
echo
echo "Plus every \`data-*\`-injected page anywhere ($DATA_COUNT total) and all shared CSS. No script edits in these zones."
echo

echo "## Safe candidate zones (link-only, future scoped PRs)"
echo
echo "Static, low-risk pages that are **missing canonical CSS** AND **not** \`data-*\`-injected AND **not** in a high-risk directory. These are the only obvious link-only candidates (each still needs a per-page check before editing):"
echo
HIRISK_GREP="$(printf '^%s/\n' "${HIRISK_DIRS[@]}" | paste -sd'|' -)"
SAFE="$(comm -23 <(printf '%s\n' "$MISSING_TOKEN" | sed '/^$/d' | sort) <(printf '%s\n' "$DATA_PAGES" | sed '/^$/d' | sort) | grep -vE "$HIRISK_GREP" || true)"
SAFE_COUNT=$(printf '%s\n' "$SAFE" | sed '/^$/d' | wc -l | tr -d ' ')
echo "Count: **$SAFE_COUNT** candidate pages."
echo
echo "| Directory | Candidate pages |"
echo "|---|---|"
printf '%s\n' "$SAFE" | sed '/^$/d' | topdir | sort | uniq -c | sort -rn | awk '{printf "| %s | %s |\n",$2,$1}'
echo
echo "<details><summary>Full safe-candidate list</summary>"
echo
printf '%s\n' "$SAFE" | sed '/^$/d' | sed 's/^/- /'
echo
echo "</details>"
echo

echo "## Recommended next PR sequence"
echo
echo "1. Keep this detector as the standing read-only audit (re-run before/after any brand work)."
echo "2. Scoped report: reconcile the multiple \`--color-brand\`/orange token definitions and any \`!important\` hardcodes in \`brand.css\` (report only; load-bearing)."
echo "3. Scoped report: verify and propose archival of brand-fix CSS files linked by 0 pages (confirm not JS-injected first)."
echo "4. Link-only PR on the vetted **safe candidate zones** above (static pages only; attach before/after screenshots)."
echo "5. One scoped report per high-risk zone, in order: \`answers/\` (lowest) -> static \`institutional/\` -> \`deep-dives/\` -> \`paths/\` -> \`interactive-demos/\` -> quizzes/AI."
echo "6. Separate scoped review of \`brand-consistency.css\` (load-bearing overlay)."
echo
echo "_No giant PRs. No edits to tools/demos/quizzes/paths/deep-dives/shared CSS/data-injected pages without a scoped report first. Preserve semantic state colors and child-brand accents._"
} > "$REPORT.tmp" && mv "$REPORT.tmp" "$REPORT"   # atomic write: no partial reads

# --- Final confirmation ------------------------------------------------------
echo "Report written: $REPORT"
echo "Scanned HTML: $TOTAL | missing-canonical: $MISSING_COUNT | hardcoded orange: $HARDCODE_COUNT | inline orange: $INLINE_COUNT | data-* pages: $DATA_COUNT"
echo "Detection only. No source files edited."
