name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps (best-effort)
        run: |
          npm ci || npm install || true
      - name: Serve static (8080)
        run: |
          python3 -m http.server 8080 &
          echo $! > server.pid
      - name: Smoke test pages
        run: |
          sleep 2
          curl -sSfI http://localhost:8080/index.html
          curl -sSfI http://localhost:8080/ai-agents/index.html
          curl -sSfI http://localhost:8080/analytics/index.html
          curl -sSfI http://localhost:8080/modules/cbdc-vs-bitcoin.html
      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
